FROM node:18-alpine3.15

WORKDIR /app

ARG REACT_APP_BACKEND_URL
ENV REACT_APP_BACKEND_URL "$REACT_APP_BACKEND_URL"

ARG REACT_APP_CLIENT_ID
ENV REACT_APP_CLIENT_ID "$REACT_APP_CLIENT_ID"

ARG REACT_APP_USER_POOL_ID
ENV REACT_APP_USER_POOL_ID "$REACT_APP_USER_POOL_ID"

COPY package.json ./
COPY package-lock.json ./

RUN npm install --force

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
