const FILTER_ACTIONS = {
  SET_RECIPIENT_LABELS : "SET_RECIPIENT_LABELS",
  SET_SCANNING_FLOW_LABELS : "SET_SCANNING_FLOW_LABELS",
  SET_ACCOUNT_LABELS : "SET_ACCOUNT_LABELS",
  SET_SELECTED_SCANNING_FLOW_LABELS : "SET_SELECTED_SCANNING_FLOW_LABELS",
  SET_SELECTED_RECIPIENT_LABELS : "SET_SELECTED_RECIPIENT_LABELS",
  SET_SELECTED_ACCOUNT_LABELS : "SET_SELECTED_ACCOUNT_LABELS",
  SET_DATE : "SET_DATE",
  FETCH_FILTERS_DATA : "FETCH_FILTERS_DATA"
}

export default FILTER_ACTIONS