const TABLE_ACTIONS = {
  SET_ORDER : "SET_ORDER",
  SET_ORDERBY : "SET_ORDERBY",
  SET_PAGE : "SET_PAGE",
  SET_PAGE_SIZE : "SET_PAGE_SIZE",
  SET_ROW_COUNT : "SET_ROW_COUNT",
  SET_ROWS : "SET_ROWS",
  FETCH_TABLE_DATA : "FETCH_TABLE_DATA",
  SET_SELECTED_ROWS : "SET_SELECTED_ROWS"
}

export default TABLE_ACTIONS
